name: distcheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # TODO get rid of this step once the popt dep has been removed
    - name: prep
      run: sudo apt -y install libpopt-dev
    - name: make
      run: make
    - name: make check
      run: make check
    # TODO add make distcheck once implemented
